language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: master